language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: master